package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private String id;
	private String username;
	private String password;
	private String gender;
	private String telephone;
	private String position;
	private Set products = new HashSet(0);
	private Set caseinfos = new HashSet(0);
	private Set companyinfos = new HashSet(0);
	private Set newses = new HashSet(0);

	public Admin() {
	}

	public Admin(String id) {
		this.id = id;
	}

	public Admin(String id, String username, String password, String gender, String telephone, String position,
			Set products, Set caseinfos, Set companyinfos, Set newses) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.gender = gender;
		this.telephone = telephone;
		this.position = position;
		this.products = products;
		this.caseinfos = caseinfos;
		this.companyinfos = companyinfos;
		this.newses = newses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

	public Set getCaseinfos() {
		return this.caseinfos;
	}

	public void setCaseinfos(Set caseinfos) {
		this.caseinfos = caseinfos;
	}

	public Set getCompanyinfos() {
		return this.companyinfos;
	}

	public void setCompanyinfos(Set companyinfos) {
		this.companyinfos = companyinfos;
	}

	public Set getNewses() {
		return this.newses;
	}

	public void setNewses(Set newses) {
		this.newses = newses;
	}

}
