package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Caseinfo generated by hbm2java
 */
public class Caseinfo implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private String title;
	private String pictureName;
	private String picturePath;
	private String caseDescription;
	private Date caseAddtime;

	public Caseinfo() {
	}

	public Caseinfo(Admin admin, String title, String pictureName, String picturePath, String caseDescription,
			Date caseAddtime) {
		this.admin = admin;
		this.title = title;
		this.pictureName = pictureName;
		this.picturePath = picturePath;
		this.caseDescription = caseDescription;
		this.caseAddtime = caseAddtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPictureName() {
		return this.pictureName;
	}

	public void setPictureName(String pictureName) {
		this.pictureName = pictureName;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public String getCaseDescription() {
		return this.caseDescription;
	}

	public void setCaseDescription(String caseDescription) {
		this.caseDescription = caseDescription;
	}

	public Date getCaseAddtime() {
		return this.caseAddtime;
	}

	public void setCaseAddtime(Date caseAddtime) {
		this.caseAddtime = caseAddtime;
	}

}
