package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Companyinfo generated by hbm2java
 */
public class Companyinfo implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private String name;
	private String address;
	private String phone;
	private String fax;
	private String linkman;
	private String telepbone;
	private String email;
	private String url;
	private String qq;
	private Date addtime;

	public Companyinfo() {
	}

	public Companyinfo(Admin admin, String name, String address, String phone, String fax, String linkman,
			String telepbone, String email, String url, String qq, Date addtime) {
		this.admin = admin;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.fax = fax;
		this.linkman = linkman;
		this.telepbone = telepbone;
		this.email = email;
		this.url = url;
		this.qq = qq;
		this.addtime = addtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getLinkman() {
		return this.linkman;
	}

	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	public String getTelepbone() {
		return this.telepbone;
	}

	public void setTelepbone(String telepbone) {
		this.telepbone = telepbone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}
