package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private Newstype newstype;
	private String title;
	private String context;
	private String picturePath;
	private Date addtime;

	public News() {
	}

	public News(Admin admin, Newstype newstype, String title, String context, String picturePath, Date addtime) {
		this.admin = admin;
		this.newstype = newstype;
		this.title = title;
		this.context = context;
		this.picturePath = picturePath;
		this.addtime = addtime;
	}

	public Integer getId() {
		return this.id;
	}

	
	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Newstype getNewstype() {
		return this.newstype;
	}

	public void setNewstype(Newstype newstype) {
		this.newstype = newstype;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}
