package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private Integer id;
	private Admin admin;
	private Productype productype;
	private String title;
	private String picturename;
	private String picturePath;
	private String pictureDescption;
	private Date pictureAddtime;

	public Product() {
	}

	public Product(Admin admin, Productype productype, String title, String picturename, String picturePath,
			String pictureDescption, Date pictureAddtime) {
		this.admin = admin;
		this.productype = productype;
		this.title = title;
		this.picturename = picturename;
		this.picturePath = picturePath;
		this.pictureDescption = pictureDescption;
		this.pictureAddtime = pictureAddtime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Admin getAdmin() {
		return this.admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public Productype getProductype() {
		return this.productype;
	}

	public void setProductype(Productype productype) {
		this.productype = productype;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getPicturename() {
		return this.picturename;
	}

	public void setPicturename(String picturename) {
		this.picturename = picturename;
	}

	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	public String getPictureDescption() {
		return this.pictureDescption;
	}

	public void setPictureDescption(String pictureDescption) {
		this.pictureDescption = pictureDescption;
	}

	public Date getPictureAddtime() {
		return this.pictureAddtime;
	}

	public void setPictureAddtime(Date pictureAddtime) {
		this.pictureAddtime = pictureAddtime;
	}

}
