package com.baizhi.cooler.domain;
// Generated 2018-11-3 16:12:45 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Productype generated by hbm2java
 */
public class Productype implements java.io.Serializable {

	private int id;
	private String typename;
	private Set products = new HashSet(0);

	public Productype() {
	}

	public Productype(int id) {
		this.id = id;
	}

	public Productype(int id, String typename, Set products) {
		this.id = id;
		this.typename = typename;
		this.products = products;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public Set getProducts() {
		return this.products;
	}

	public void setProducts(Set products) {
		this.products = products;
	}

}
