package com.leo.e3mall.pojo;
// Generated 2019-1-2 13:32:37 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TbContent generated by hbm2java
 * 内容
 */
public class Content implements java.io.Serializable {

	private Long id;
	private long categoryId;//分类的id
	private String title;//标题
	private String subTitle;//子标题
	private String titleDesc;//标题描述
	private String url;//路径
	private String pic;//图片1
	private String pic2;//图片2
	private String content;//内容
	private Date created;//添加时间
	private Date updated;//更新时间

	public Content() {
	}

	public Content(long categoryId) {
		this.categoryId = categoryId;
	}

	public Content(long categoryId, String title, String subTitle, String titleDesc, String url, String pic,
			String pic2, String content, Date created, Date updated) {
		this.categoryId = categoryId;
		this.title = title;
		this.subTitle = subTitle;
		this.titleDesc = titleDesc;
		this.url = url;
		this.pic = pic;
		this.pic2 = pic2;
		this.content = content;
		this.created = created;
		this.updated = updated;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getSubTitle() {
		return this.subTitle;
	}

	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	public String getTitleDesc() {
		return this.titleDesc;
	}

	public void setTitleDesc(String titleDesc) {
		this.titleDesc = titleDesc;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPic() {
		return this.pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public String getPic2() {
		return this.pic2;
	}

	public void setPic2(String pic2) {
		this.pic2 = pic2;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
