package com.leo.bos.domain;
// Generated 2018-10-9 18:00:39 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * 工单
 * QpWorkbill generated by hbm2java
 */
@Entity
@Table(name = "qp_workbill", catalog = "bos")
public class QpWorkbill implements java.io.Serializable {

	private String id;//工单号
	//一对多
	private QpNoticebill qpNoticebill;//业务通知单号
	private BcStaff bcStaff;//取派员编号
	
	private String type;//工单类型 :新，追 ，改，销
	private String pickstate;//取件状态 ：未取件，取件中，已取件
	private Date buildtime;//工单生成时间
	private Integer attachbilltimes;//追单次数
	private String remark;//备注
	public static final String TYPE_1="新单";
	public static final String TYPE_2="追单";
	public static final String TYPE_3="改单";
	public static final String TYPE_4="销单";
	
	public static final String PICKSTATE_NO="未取件";
	public static final String PICKSTATE_RUNNING="取件中";
	public static final String PICKSTATE_YES="已取件";
	
	public QpWorkbill() {
	}

	public QpWorkbill(String id, Date buildtime) {
		this.id = id;
		this.buildtime = buildtime;
	}

	public QpWorkbill(String id, QpNoticebill qpNoticebill, BcStaff bcStaff, String type, String pickstate,
			Date buildtime, Integer attachbilltimes, String remark) {
		this.id = id;
		this.qpNoticebill = qpNoticebill;
		this.bcStaff = bcStaff;
		this.type = type;
		this.pickstate = pickstate;
		this.buildtime = buildtime;
		this.attachbilltimes = attachbilltimes;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noticebill_id")
	public QpNoticebill getQpNoticebill() {
		return this.qpNoticebill;
	}

	public void setQpNoticebill(QpNoticebill qpNoticebill) {
		this.qpNoticebill = qpNoticebill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "staff_id")
	public BcStaff getBcStaff() {
		return this.bcStaff;
	}

	public void setBcStaff(BcStaff bcStaff) {
		this.bcStaff = bcStaff;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "pickstate", length = 20)
	public String getPickstate() {
		return this.pickstate;
	}

	public void setPickstate(String pickstate) {
		this.pickstate = pickstate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "buildtime", nullable = false, length = 19)
	public Date getBuildtime() {
		return this.buildtime;
	}

	public void setBuildtime(Date buildtime) {
		this.buildtime = buildtime;
	}

	@Column(name = "attachbilltimes")
	public Integer getAttachbilltimes() {
		return this.attachbilltimes;
	}

	public void setAttachbilltimes(Integer attachbilltimes) {
		this.attachbilltimes = attachbilltimes;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
