package com.leo.course.scheduling.domain;
// Generated 2019-2-27 18:43:57 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Classes generated by hbm2java
 */
public class Classes implements java.io.Serializable {

	private Integer id;
	private String department;//院系
	private String specialty;//专业
	private String description;//描述
	private String name;//名称
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
	private Date addtime;
	private String flag;
	private Set timetables = new HashSet(0);
	private Set students = new HashSet(0);

	public Classes() {
	}

	public Classes(String department, String specialty, String description, String name, Date addtime, Set timetables,
			Set students) {
		this.department = department;
		this.specialty = specialty;
		this.description = description;
		this.name = name;
		this.addtime = addtime;
		this.timetables = timetables;
		this.students = students;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getAddtime() {
		return this.addtime;
	}

	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	public Set getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set timetables) {
		this.timetables = timetables;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

	/**
	 * @return the flag
	 */
	public String getFlag() {
		return flag;
	}

	/**
	 * @param flag the flag to set
	 */
	public void setFlag(String flag) {
		this.flag = flag;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Classes [id=" + id + ", department=" + department + ", specialty=" + specialty + ", description="
				+ description + ", name=" + name + ", addtime=" + addtime + "]";
	}

}
