package com.leo.course.scheduling.domain;
// Generated 2019-2-27 18:43:57 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.omg.CosNaming.NamingContextExtPackage.StringNameHelper;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private Integer id;
	private Teacher teacher;
	private String subcode;
	private String subname;
	private String subcredit;//学分
	private String subtime;//学时
	private String subdescription;
	private Set timetables = new HashSet(0);
	private Integer teacherid;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
	private Date addtime;
	private String majorno;

	private String subtype;
	/**
	 * @return the subtype
	 */
	public String getSubtype() {
		return subtype;
	}

	/**
	 * @param subtype the subtype to set
	 */
	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	private String tereoff;
	private String teachnumber;
	private String name;
	
	public Subject(Integer id, Teacher teacher, String subcode, String subname, String subcredit, String subtime,
			String subdescription, Set timetables, Integer teacherid, Date addtime, String subtype, String tereoff,
			String teachnumber, String name, String majorno) {
		super();
		this.id = id;
		this.teacher = teacher;
		this.subcode = subcode;
		this.subname = subname;
		this.subcredit = subcredit;
		this.subtime = subtime;
		this.subdescription = subdescription;
		this.timetables = timetables;
		this.teacherid = teacherid;
		this.addtime = addtime;
		this.subtype = subtype;
		this.tereoff = tereoff;
		this.teachnumber = teachnumber;
		this.name = name;
		this.majorno = majorno;
	}

	/**
	 * @return the majorno
	 */
	public String getMajorno() {
		return majorno;
	}

	/**
	 * @param majorno the majorno to set
	 */
	public void setMajorno(String majorno) {
		this.majorno = majorno;
	}

	/**
	 * @return the teacherid
	 */
	public Integer getTeacherid() {
		return teacherid;
	}

	public Subject(Integer id, Teacher teacher, String subcode, String subname, String subcredit, String subtime,
			String subdescription, Set timetables, Integer teacherid, Date addtime) {
		super();
		this.id = id;
		this.teacher = teacher;
		this.subcode = subcode;
		this.subname = subname;
		this.subcredit = subcredit;
		this.subtime = subtime;
		this.subdescription = subdescription;
		this.timetables = timetables;
		this.teacherid = teacherid;
		this.addtime = addtime;
	}

	/**
	 * @param teacherid the teacherid to set
	 */
	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

	/**
	 * @return the subtime
	 */
	public String getSubtime() {
		return subtime;
	}

	/**
	 * @param subtime the subtime to set
	 */
	public void setSubtime(String subtime) {
		this.subtime = subtime;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Subject [id=" + id + ", teacher=" + teacher + ", subcode=" + subcode + ", subname=" + subname
				+ ", subcredit=" + subcredit + ", subtime=" + subtime + ", subdescription=" + subdescription
				+ ", timetables=" + timetables + ", teacherid=" + teacherid + ", addtime=" + addtime + ", subtype="
				+ subtype + ", tereoff=" + tereoff + ", teachnumber=" + teachnumber + ", name=" + name + "]";
	}

	

	public Subject() {
	}



	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getSubcode() {
		return this.subcode;
	}

	public void setSubcode(String subcode) {
		this.subcode = subcode;
	}

	public String getSubname() {
		return this.subname;
	}

	public void setSubname(String subname) {
		this.subname = subname;
	}

	public String getSubcredit() {
		return this.subcredit;
	}

	public void setSubcredit(String subcredit) {
		this.subcredit = subcredit;
	}

	public String getSubdescription() {
		return this.subdescription;
	}

	public void setSubdescription(String subdescription) {
		this.subdescription = subdescription;
	}

	public Set getTimetables() {
		return this.timetables;
	}

	public void setTimetables(Set timetables) {
		this.timetables = timetables;
	}

	/**
	 * @return the addtime
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * @param addtime the addtime to set
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * @return the tereoff
	 */
	public String getTereoff() {
		return tereoff;
	}

	/**
	 * @param tereoff the tereoff to set
	 */
	public void setTereoff(String tereoff) {
		this.tereoff = tereoff;
	}

	/**
	 * @return the teachnumber
	 */
	public String getTeachnumber() {
		return teachnumber;
	}

	/**
	 * @param teachnumber the teachnumber to set
	 */
	public void setTeachnumber(String teachnumber) {
		this.teachnumber = teachnumber;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

}
