package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Oders generated by hbm2java
 * 订单详情
 */
@Entity
@Table(name = "oders", catalog = "hotel")
public class Oders implements java.io.Serializable {

	private int id;
	private Order order;//订单id 多对一
	private Room room;//房间号 多对一
	private String price;//价格
	private String remark;//标注

	public Oders() {
	}

	public Oders(int id) {
		this.id = id;
	}

	public Oders(int id, Order order, Room room, String price, String remark) {
		this.id = id;
		this.order = order;
		this.room = room;
		this.price = price;
		this.remark = remark;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "room_id")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "price")
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Oders [id=" + id + ", order=" + order + ", room=" + room + ", price=" + price + ", remark=" + remark
				+ "]";
	}

}
