package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.omg.CosNaming.NamingContextExtPackage.StringNameHelper;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Order generated by hbm2java
 * 订单
 */
@Entity
@Table(name = "order", catalog = "hotel")
public class Order implements java.io.Serializable {

	private int id;
	private User user;//用户id
	private String time;//时间
	private String name;//姓名
	private String price;//价格
	private String address;//地址
	private String telephone;//电话
	private String startdate;//订单开始时间
	private String enddate;//订单结束时间
	private String status;//顶单状态
	private int roomid;//房间id
	private int hoteid;//酒店id;
	private int userid;
	
	private String roomname;
	private String hotelname;
	private String regioname;
	
	private String username;
	
	private String price1;
	
	/**
	 * @return the price1
	 */
	public String getPrice1() {
		return price1;
	}

	/**
	 * @param price1 the price1 to set
	 */
	public void setPrice1(String price1) {
		this.price1 = price1;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the roomname
	 */
	public String getRoomname() {
		return roomname;
	}

	/**
	 * @param roomname the roomname to set
	 */
	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	/**
	 * @return the hotelname
	 */
	public String getHotelname() {
		return hotelname;
	}

	/**
	 * @param hotelname the hotelname to set
	 */
	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	/**
	 * @return the regioname
	 */
	public String getRegioname() {
		return regioname;
	}

	/**
	 * @param regioname the regioname to set
	 */
	public void setRegioname(String regioname) {
		this.regioname = regioname;
	}

	/**
	 * @return the userid
	 */
	public int getUserid() {
		return userid;
	}

	/**
	 * @param userid the userid to set
	 */
	public void setUserid(int userid) {
		this.userid = userid;
	}

	/**
	 * @return the hoteid
	 */
	@Column(name = "hoteid")
	public int getHoteid() {
		return hoteid;
	}

	/**
	 * @param hoteid the hoteid to set
	 */
	public void setHoteid(int hoteid) {
		this.hoteid = hoteid;
	}

	private Set<Oders> oderses = new HashSet<Oders>();//订单性情，一对多
	/**
	 * @return the roomid
	 */
	public int getRoomid() {
		return roomid;
	}

	/**
	 * @param roomid the roomid to set
	 */
	public void setRoomid(int roomid){
		this.roomid = roomid;
	}



	public Order() {
	}

	public Order(int id) {
		this.id = id;
	}

	public Order(int id, User user, String time, String name, String price, String address, String telephone,
			Set<Oders> oderses) {
		this.id = id;
		this.user = user;
		this.time = time;
		this.name = name;
		this.price = price;
		this.address = address;
		this.telephone = telephone;
		this.oderses = oderses;
	}

	/**
	 * @return the startdate
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	@Column(name = "startdate")
	public String getStartdate() {
		return startdate;
	}

	/**
	 * @param startdate the startdate to set
	 */
	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	/**
	 * @return the enddate
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	@Column(name = "enddate")
	public String getEnddate() {
		return enddate;
	}

	/**
	 * @param enddate the enddate to set
	 */
	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	/**
	 * @return the status.
	 */
	@Column(name = "status")
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	@Column(name = "time", length = 19)
	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price")
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set<Oders> getOderses() {
		return this.oderses;
	}

	public void setOderses(Set<Oders> oderses) {
		this.oderses = oderses;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Order [id=" + id + ", user=" + user + ", time=" + time + ", name=" + name + ", price=" + price
				+ ", address=" + address + ", telephone=" + telephone + ", oderses=" + oderses + "]";
	}

}
