package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.omg.CosNaming.NamingContextExtPackage.StringNameHelper;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", catalog = "hotel")
public class Room implements java.io.Serializable {

	private int id;
	private Merchant merchant;//商家可以有多个房间 
	private Roomsort roomsort;//多对一
	private String name;//姓名
	private String price;//价格
	private String stutscode;//房间状态
	private String roompicture;
	
	public  static final String STUTS_YS="0";
	public  static final String STUTS_NO="1";
	
	/**
	 * 用于接收前台传输的字段
	 */
	private Integer sortid;//分类id
	
	/**
	 * 展示给前台：
	 *
	 */
	private String sortName;
	private Integer merchantid;
	
	/**
	 * @return the merchantid
	 */
	public Integer getMerchantid() {
		return merchantid;
	}

	/**
	 * @param merchantid the merchantid to set
	 */
	public void setMerchantid(Integer merchantid) {
		this.merchantid = merchantid;
	}

	/**
	 * @return the sortName
	 */
	public String getSortName() {
		return sortName;
	}

	/**
	 * @param sortName the sortName to set
	 */
	public void setSortName(String sortName) {
		this.sortName = sortName;
	}

	/**
	 * @return the sortid
	 */
	public Integer getSortid() {
		return sortid;
	}

	/**
	 * @param sortid the sortid to set
	 */
	public void setSortid(Integer sortid) {
		this.sortid = sortid;
	}

	private Set<Oders> oderses = new HashSet<Oders>(0);//一对多，一个房间有多个订单

	public Room() {
	}

	public Room(int id) {
		this.id = id;
	}

	public Room(int id, Merchant merchant, Roomsort roomsort, String name, String price, String stutscode,
			Set<Oders> oderses) {
		this.id = id;
		this.merchant = merchant;
		this.roomsort = roomsort;
		this.name = name;
		this.price = price;
		this.stutscode = stutscode;
		this.oderses = oderses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "merchant_id")
	public Merchant getMerchant() {
		return this.merchant;
	}

	public void setMerchant(Merchant merchant) {
		this.merchant = merchant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sort_id")
	public Roomsort getRoomsort() {
		return this.roomsort;
	}

	public void setRoomsort(Roomsort roomsort) {
		this.roomsort = roomsort;
	}
	/**
	 * @return the roompicture
	 */
	@Column(name = "roompicture")
	public String getRoompicture(){
		return roompicture;
	}

	/**
	 * @param roompicture the roompicture to set
	 */
	public void setRoompicture(String roompicture) {
		this.roompicture = roompicture;
	}
	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price")
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "stutscode")
	public String getStutscode() {
		return this.stutscode;
	}

	public void setStutscode(String stutscode) {
		this.stutscode = stutscode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	public Set<Oders> getOderses() {
		return this.oderses;
	}

	public void setOderses(Set<Oders> oderses) {
		this.oderses = oderses;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Room [id=" + id + ", merchant=" + merchant + ", roomsort=" + roomsort + ", name=" + name + ", price="
				+ price + ", stutscode=" + stutscode + ", oderses=" + oderses + "]";
	}

}
