package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roomsort generated by hbm2java
 * 房间分类
 */
@Entity
@Table(name = "roomsort", catalog = "hotel")
public class Roomsort implements java.io.Serializable {

	private int id;
	private String sortname;//类型名
	private String description;//描述
	private Set<Room> rooms = new HashSet<Room>(0);//一对多

	public Roomsort() {
	}

	public Roomsort(int id) {
		this.id = id;
	}

	public Roomsort(int id, String sortname, String description, Set<Room> rooms) {
		this.id = id;
		this.sortname = sortname;
		this.description = description;
		this.rooms = rooms;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sortname")
	public String getSortname() {
		return this.sortname;
	}

	public void setSortname(String sortname) {
		this.sortname = sortname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roomsort")
	public Set<Room> getRooms() {
		return this.rooms;
	}

	public void setRooms(Set<Room> rooms) {
		this.rooms = rooms;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Roomsort [id=" + id + ", sortname=" + sortname + ", description=" + description + ", rooms=" + rooms
				+ "]";
	}

}
