package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Starlevel generated by hbm2java
 * 星级
 */
@Entity
@Table(name = "starlevel", catalog = "hotel")
public class Starlevel implements java.io.Serializable {

	private int id;
	private String starname;//星级名
	private String description;//描述
	private String remark;//备注
	private Set<Merchant> merchants = new HashSet<Merchant>(0);//一对多

	public Starlevel() {
	}

	public Starlevel(int id) {
		this.id = id;
	}

	public Starlevel(int id, String starname, String description, String remark, Set<Merchant> merchants) {
		this.id = id;
		this.starname = starname;
		this.description = description;
		this.remark = remark;
		this.merchants = merchants;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "starname")
	public String getStarname() {
		return this.starname;
	}

	public void setStarname(String starname) {
		this.starname = starname;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "remark")
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "starlevel")
	public Set<Merchant> getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Set<Merchant> merchants) {
		this.merchants = merchants;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Starlevel [id=" + id + ", starname=" + starname + ", description=" + description + ", remark=" + remark
				+ ", merchants=" + merchants + "]";
	}

}
