package com.leo.hotel.domain;
// Generated 2018-11-14 13:00:41 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * User generated by hbm2java
 * 用户表
 */
@Entity
@Table(name = "user", catalog = "hotel")
public class User implements java.io.Serializable {

	private int id;
	private String username;//用户名
	private String password;//密码
	private String iccard;//身份证号
	private String gender;//性别
	private String phone;//手机
	private String address;//地址
	private String headshot;//头像
	@Transient//指定不需要映射到数据表中的属性
	private String checkcode;
	private String birthday;
	
	/**
	 * @return the birthday
	 */
	@Column(name = "birthday")
	@JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
	@DateTimeFormat(pattern="yyyy-MM-dd")
	public String getBirthday() {
		return birthday;
	}

	/**
	 * @param birthday the birthday to set
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * @return the checkcode
	 */

	public String getCheckcode() {
		return checkcode;
	}

	/**
	 * @param checkcode the checkcode to set
	 */
	public void setCheckcode(String checkcode) {
		this.checkcode = checkcode;
	}

	private Set<Order> orders = new HashSet<Order>(0);//一对多：可以有多个订单

	public User() {
	}

	public User(int id, String headshot) {
		this.id = id;
		this.headshot = headshot;
	}

	public User(int id, String username, String password, String iccard, String gender, String phone, String address,
			String headshot, Set<Order> orders) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.iccard = iccard;
		this.gender = gender;
		this.phone = phone;
		this.address = address;
		this.headshot = headshot;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Iccard")
	public String getIccard() {
		return this.iccard;
	}

	public void setIccard(String iccard) {
		this.iccard = iccard;
	}

	@Column(name = "gender")
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "phone")
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "headshot", nullable = false)
	public String getHeadshot() {
		return this.headshot;
	}

	public void setHeadshot(String headshot) {
		this.headshot = headshot;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "User [id=" + id + ", username=" + username + ", password=" + password + ", iccard=" + iccard
				+ ", gender=" + gender + ", phone=" + phone + ", address=" + address + ", headshot=" + headshot
				+ ", orders=" + orders + "]";
	}

	
	
}
