package com.leo.e3mall.pojo;
// Generated 2019-1-2 13:32:37 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * TbItemDesc generated by hbm2java
 */
public class ItemDesc implements java.io.Serializable {

	private long itemId;
	private String itemDesc;
	private Date created;
	private Date updated;

	public ItemDesc() {
	}

	public ItemDesc(long itemId) {
		this.itemId = itemId;
	}

	public ItemDesc(long itemId, String itemDesc, Date created, Date updated) {
		this.itemId = itemId;
		this.itemDesc = itemDesc;
		this.created = created;
		this.updated = updated;
	}

	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	public String getItemDesc() {
		return this.itemDesc;
	}

	public void setItemDesc(String itemDesc) {
		this.itemDesc = itemDesc;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

}
