package com.leo.course.scheduling.domain;
// Generated 2019-2-27 18:43:57 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer id;
	private Classes classes;
	private String number;
	private String name;
	private String sex;
	private String iccode;
	private String image;
	@DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
	@JsonFormat(pattern = "yyyy-MM-dd", timezone="GMT+8")
	private Date addtime;
	private int classid;
	public Student() {
	}

	
	public Student(Integer id, Classes classes, String number, String name, String sex, String iccode, String image,
			Date addtime) {
		super();
		this.id = id;
		this.classes = classes;
		this.number = number;
		this.name = name;
		this.sex = sex;
		this.iccode = iccode;
		this.image = image;
		this.addtime = addtime;
	}


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Classes getClasses() {
		return this.classes;
	}

	public void setClasses(Classes classes) {
		this.classes = classes;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getIccode() {
		return this.iccode;
	}

	public void setIccode(String iccode) {
		this.iccode = iccode;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Student [id=" + id + ", classes=" + classes + ", number=" + number + ", name=" + name + ", sex=" + sex
				+ ", iccode=" + iccode + ", image=" + image + ", addtime=" + addtime + ", classid=" + classid + "]";
	}


	/**
	 * @return the addtime
	 */
	public Date getAddtime() {
		return addtime;
	}


	/**
	 * @param addtime the addtime to set
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}


	/**
	 * @return the classid
	 */
	public int getClassid() {
		return classid;
	}


	/**
	 * @param classid the classid to set
	 */
	public void setClassid(int classid) {
		this.classid = classid;
	}

}
